openapi: 3.0.0
info:
  title: Orders API
  version: v1
paths:
  /orders:
    get:
      description: Retrieve or search the list of orders
      parameters:
        -
          name: account-id
          in: query
          schema:
            $ref: "#/components/schemas/AccountID"
      requestBody:
        content: {}
      responses:
        "200":
          description: Happy Path retrieve
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"
        "500":
          description: A server-side error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    example: Unexpected Internal error occured
                    type: string
components:
  schemas:
    AccountID:
      example: acct567
      type: string
      pattern: ^acct\d+$
    Order:
      type: object
      required:
        - order-id
        - account-id
      properties:
        order-id:
          example: ord123
          type: string
          pattern: ^ord\d+$
        account-id:
          $ref: "#/components/schemas/AccountID"
        total-price:
          example: 1
          type: number
          format: float
